import {readFileSync,writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const snapshots=Object.fromEntries([650,1200,2000].map(count=>[count,JSON.parse(readFileSync(resolve(root,`assets/pile-${count}.json`),'utf8'))]));
writeFileSync(resolve(root,'js/snapshots.js'),'// Pre-settled starting poses. Generated by scripts/settle.mjs.\nexport const SNAPSHOTS = '+JSON.stringify(snapshots)+';\n');
const modules=['math','catalog','geometry','physics','shaders','renderer','audio','input','snapshots','app'];
let bundle='/* HEAVY / PLAY — original code, MIT license. No runtime dependencies. */\n(()=>{\n"use strict";\nconst __modules=Object.create(null);\n';
for(const name of modules){let code=readFileSync(resolve(root,`js/${name}.js`),'utf8');const exports=[...code.matchAll(/export\s+(?:const|let|function|class)\s+(\w+)/g)].map(m=>m[1]);code=code.replace(/import\s+\{([^}]+)\}\s+from\s+['"]\.\/(\w+)\.js['"];?/g,(_,names,module)=>`const {${names}} = __modules[${JSON.stringify(module)}];`);code=code.replace(/export\s+(?=const|let|function|class)/g,'');bundle+=`\n__modules[${JSON.stringify(name)}]=(()=>{\n${code}\nreturn {${exports.join(',')}};\n})();\n`;}
bundle+='})();\n';writeFileSync(resolve(root,'js/app.bundle.js'),bundle);
let html=readFileSync(resolve(root,'index.html'),'utf8');html=html.replace('<script type="module" src="./js/app.js"></script>','<script defer src="./js/app.bundle.js"></script>');writeFileSync(resolve(root,'index.html'),html);
let preview=html.replace('<link rel="stylesheet" href="./css/style.css">',`<style>\n${readFileSync(resolve(root,'css/style.css'),'utf8')}\n</style>`).replace('<script defer src="./js/app.bundle.js"></script>',`<script>\n${bundle.replace(/<\/script/gi,'<\\/script')}\n</script>`);
const destination=process.argv[2]?resolve(process.argv[2]):resolve(root,'../HEAVY-PLAY-preview.html');writeFileSync(destination,preview);console.log('Built split-file site and preview:',destination,Math.round(bundle.length/1024)+' KiB JS');
